# Generated by Django 4.2.21 on 2025-10-28 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_enunciado', models.TextField()),
                ('nivel', models.CharField(blank=True, choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], max_length=20, null=True)),
                ('letra_correta', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'db_table': 'perguntas',
            },
        ),
        migrations.CreateModel(
            name='PerguntaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.ForeignKey(db_column='id_obra', on_delete=django.db.models.deletion.CASCADE, to='content.obra')),
                ('pergunta', models.ForeignKey(db_column='id_pergunta', on_delete=django.db.models.deletion.CASCADE, to='quiz.pergunta')),
            ],
            options={
                'db_table': 'pergunta_obra',
                'unique_together': {('pergunta', 'obra')},
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='obras',
            field=models.ManyToManyField(related_name='perguntas', through='quiz.PerguntaObra', to='content.obra'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='usuarios',
            field=models.ManyToManyField(related_name='perguntas', through='progress.PerguntaUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra_alternativa', models.CharField(max_length=1)),
                ('texto_alternativa', models.TextField()),
                ('pergunta', models.ForeignKey(db_column='id_pergunta', on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='quiz.pergunta')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'db_table': 'alternativas',
            },
        ),
    ]
