# Generated by Django 4.2.21 on 2025-06-30 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=50)),
                ('nome_obra', models.CharField(max_length=50)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'db_table': 'obras',
            },
        ),
        migrations.CreateModel(
            name='UsuarioObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.ForeignKey(db_column='id_obra', on_delete=django.db.models.deletion.CASCADE, to='content.obra')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_obra',
                'unique_together': {('usuario', 'obra')},
            },
        ),
        migrations.AddField(
            model_name='obra',
            name='usuarios',
            field=models.ManyToManyField(related_name='obras', through='content.UsuarioObra', to=settings.AUTH_USER_MODEL),
        ),
    ]
