# Generated by Django 4.2.21 on 2025-06-30 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntausuario',
            name='pergunta',
            field=models.ForeignKey(db_column='id_pergunta', on_delete=django.db.models.deletion.CASCADE, to='quiz.pergunta'),
        ),
        migrations.AddField(
            model_name='perguntausuario',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='perguntausuario',
            unique_together={('pergunta', 'usuario')},
        ),
    ]
