# Generated by Django 4.2.21 on 2025-10-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_usuario', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'pergunta_usuario',
            },
        ),
    ]
