# Generated by Django 4.2.21 on 2025-10-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='pontos_experiencia',
            field=models.IntegerField(default=0),
        ),
    ]
