# Generated by Django 4.2.21 on 2025-10-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('feedback', '0002_alter_avaliacao_pontos_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='obra',
            field=models.ForeignKey(blank=True, db_column='id_obra', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_obra', to='content.obra'),
        ),
    ]
